### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by deathdragon1987** [owk880301/TwitchRecover_cloudflare_bypass#3]
Error in script as follows:

C:\Users\user1\Desktop\TwitchRecover_cloudflare_bypass-main>recover.py
Find the broadcast link you want from Twitchtracker or Streamscharts site.
Enter the link:https://twitchtracker.com/buddha/streams/43621999851
Date and Time are checking...
C:\Users\user1\Desktop\TwitchRecover_cloudflare_bypass-main\recover.py:188: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(r.content, 'html.parser')
It seems you even copy and paste your api key, please paste it and try again.
Traceback (most recent call last):
  File "C:\Users\user1\Desktop\TwitchRecover_cloudflare_bypass-main\recover.py", line 291, in <module>
    timestamp = linkTimeCheck(link)
                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\Desktop\TwitchRecover_cloudflare_bypass-main\recover.py", line 195, in linkTimeCheck
    content = meta_element.get("content")
              ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by deathdragon1987** [comment]
Error only seems to occur when using Twitchtracker. Streamcharts seems to work fine
